import { CategoryItem, Transaction, Budget, SavingsGoal, AppSettings } from '../types/finance';

export const DEFAULT_CATEGORIES: CategoryItem[] = [
  { id: 'cat-food', name: 'Food & Dining', icon: 'UtensilsCrossed', color: '#F97316', type: 'expense' },
  { id: 'cat-shopping', name: 'Shopping', icon: 'ShoppingBag', color: '#EC4899', type: 'expense' },
  { id: 'cat-travel', name: 'Travel & Commute', icon: 'Plane', color: '#3B82F6', type: 'expense' },
  { id: 'cat-bills', name: 'Bills & Utilities', icon: 'Receipt', color: '#EF4444', type: 'expense' },
  { id: 'cat-entertainment', name: 'Entertainment', icon: 'Film', color: '#8B5CF6', type: 'expense' },
  { id: 'cat-education', name: 'Education', icon: 'GraduationCap', color: '#06B6D4', type: 'expense' },
  { id: 'cat-health', name: 'Health & Fitness', icon: 'HeartPulse', color: '#10B981', type: 'expense' },
  { id: 'cat-other-exp', name: 'Other Expenses', icon: 'MoreHorizontal', color: '#64748B', type: 'expense' },
  { id: 'cat-salary', name: 'Salary', icon: 'Wallet', color: '#059669', type: 'income' },
  { id: 'cat-freelance', name: 'Freelance & Projects', icon: 'Briefcase', color: '#6366F1', type: 'income' },
  { id: 'cat-investments', name: 'Investments & Returns', icon: 'TrendingUp', color: '#14B8A6', type: 'income' },
];

function getRelativeDateStr(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
}

export function generateSeedTransactions(): Transaction[] {
  return [
    {
      id: 'tx-1',
      type: 'income',
      amount: 45000,
      description: 'Monthly Tech Salary',
      category: 'Salary',
      date: getRelativeDateStr(2),
      paymentMethod: 'Bank Transfer',
      notes: 'Direct deposit from Acme Corp',
      createdAt: Date.now() - 1000 * 60 * 60 * 48,
    },
    {
      id: 'tx-2',
      type: 'expense',
      amount: 3200,
      description: 'Weekly Organic Grocery Run',
      category: 'Food & Dining',
      date: getRelativeDateStr(1),
      paymentMethod: 'Card',
      notes: 'Supermarket fresh produce and pantry restock',
      createdAt: Date.now() - 1000 * 60 * 60 * 24,
    },
    {
      id: 'tx-3',
      type: 'expense',
      amount: 1450,
      description: 'Fiber Internet & Mobile Bill',
      category: 'Bills & Utilities',
      date: getRelativeDateStr(2),
      paymentMethod: 'UPI',
      notes: 'High-speed broadband monthly auto-pay',
      createdAt: Date.now() - 1000 * 60 * 60 * 40,
    },
    {
      id: 'tx-4',
      type: 'expense',
      amount: 4800,
      description: 'Noise Cancelling Headphones',
      category: 'Shopping',
      date: getRelativeDateStr(3),
      paymentMethod: 'Card',
      notes: 'Amazon Prime electronics sale',
      createdAt: Date.now() - 1000 * 60 * 60 * 72,
    },
    {
      id: 'tx-5',
      type: 'expense',
      amount: 850,
      description: 'Cab Rides & Metro Pass',
      category: 'Travel & Commute',
      date: getRelativeDateStr(4),
      paymentMethod: 'UPI',
      notes: 'Weekly office commute',
      createdAt: Date.now() - 1000 * 60 * 60 * 90,
    },
    {
      id: 'tx-6',
      type: 'income',
      amount: 12500,
      description: 'Web Design Freelance Milestone',
      category: 'Freelance & Projects',
      date: getRelativeDateStr(5),
      paymentMethod: 'Bank Transfer',
      notes: 'Client UI sprint review approved',
      createdAt: Date.now() - 1000 * 60 * 60 * 120,
    },
    {
      id: 'tx-7',
      type: 'expense',
      amount: 999,
      description: 'Streaming & Cloud Subscriptions',
      category: 'Entertainment',
      date: getRelativeDateStr(6),
      paymentMethod: 'Card',
      notes: 'Netflix, Spotify & GitHub Pro renewal',
      createdAt: Date.now() - 1000 * 60 * 60 * 140,
    },
    {
      id: 'tx-8',
      type: 'expense',
      amount: 1800,
      description: 'Quarterly Gym Membership',
      category: 'Health & Fitness',
      date: getRelativeDateStr(8),
      paymentMethod: 'UPI',
      notes: 'Fitness center pass and locker access',
      createdAt: Date.now() - 1000 * 60 * 60 * 192,
    },
    {
      id: 'tx-9',
      type: 'expense',
      amount: 1650,
      description: 'Weekend Dining with Friends',
      category: 'Food & Dining',
      date: getRelativeDateStr(10),
      paymentMethod: 'UPI',
      notes: 'Artisan pizza bistro dinner',
      createdAt: Date.now() - 1000 * 60 * 60 * 240,
    },
    {
      id: 'tx-10',
      type: 'expense',
      amount: 2200,
      description: 'TypeScript Masterclass Course',
      category: 'Education',
      date: getRelativeDateStr(14),
      paymentMethod: 'Card',
      notes: 'Advanced frontend architecture certification',
      createdAt: Date.now() - 1000 * 60 * 60 * 336,
    },
    {
      id: 'tx-11',
      type: 'expense',
      amount: 1200,
      description: 'Gasoline & Vehicle Service',
      category: 'Travel & Commute',
      date: getRelativeDateStr(18),
      paymentMethod: 'Cash',
      notes: 'Full tank fuel top-up',
      createdAt: Date.now() - 1000 * 60 * 60 * 432,
    },
    {
      id: 'tx-12',
      type: 'income',
      amount: 3200,
      description: 'Dividend Payout on Index Fund',
      category: 'Investments & Returns',
      date: getRelativeDateStr(22),
      paymentMethod: 'Bank Transfer',
      notes: 'Quarterly mutual fund return payout',
      createdAt: Date.now() - 1000 * 60 * 60 * 520,
    },
    {
      id: 'tx-13',
      type: 'expense',
      amount: 2100,
      description: 'New Books & Office Supplies',
      category: 'Shopping',
      date: getRelativeDateStr(25),
      paymentMethod: 'Card',
      notes: 'Desk organizer, mechanical keyboard wrist rest',
      createdAt: Date.now() - 1000 * 60 * 60 * 600,
    },
    {
      id: 'tx-14',
      type: 'expense',
      amount: 1100,
      description: 'Dinner delivery & Snacks',
      category: 'Food & Dining',
      date: getRelativeDateStr(28),
      paymentMethod: 'UPI',
      notes: 'Late night coding session order',
      createdAt: Date.now() - 1000 * 60 * 60 * 672,
    },
    {
      id: 'tx-15',
      type: 'income',
      amount: 45000,
      description: 'Previous Month Tech Salary',
      category: 'Salary',
      date: getRelativeDateStr(32),
      paymentMethod: 'Bank Transfer',
      notes: 'Direct deposit',
      createdAt: Date.now() - 1000 * 60 * 60 * 768,
    },
    {
      id: 'tx-16',
      type: 'expense',
      amount: 3400,
      description: 'Electricity & Water Utility Bill',
      category: 'Bills & Utilities',
      date: getRelativeDateStr(35),
      paymentMethod: 'UPI',
      notes: 'Municipal utility invoice',
      createdAt: Date.now() - 1000 * 60 * 60 * 840,
    },
  ];
}

export const DEFAULT_BUDGETS: Budget[] = [
  { id: 'b-1', category: 'Food & Dining', amount: 8000, period: 'monthly' },
  { id: 'b-2', category: 'Shopping', amount: 7500, period: 'monthly' },
  { id: 'b-3', category: 'Travel & Commute', amount: 4000, period: 'monthly' },
  { id: 'b-4', category: 'Bills & Utilities', amount: 5000, period: 'monthly' },
  { id: 'b-5', category: 'Entertainment', amount: 2500, period: 'monthly' },
  { id: 'b-6', category: 'Health & Fitness', amount: 3000, period: 'monthly' },
];

export const DEFAULT_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'sg-1',
    title: 'MacBook Pro M3 Max',
    targetAmount: 180000,
    currentAmount: 125000,
    deadline: '2026-12-31',
    color: '#3B82F6',
    icon: 'Laptop',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
  },
  {
    id: 'sg-2',
    title: 'Emergency Safety Fund',
    targetAmount: 100000,
    currentAmount: 84000,
    deadline: '2026-11-15',
    color: '#10B981',
    icon: 'ShieldCheck',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
  },
  {
    id: 'sg-3',
    title: 'Japan Autumn Trip',
    targetAmount: 150000,
    currentAmount: 48000,
    deadline: '2027-04-10',
    color: '#EC4899',
    icon: 'Compass',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  theme: 'system',
  accentColor: 'emerald',
  currency: 'INR',
  userName: 'Kajal',
};
